sudo: false
language: java
jdk:
- oraclejdk8
script: mvn clean deploy -Ddetail=true -settings=settings.xml
env:
  global:
  - secure: WjfswfDCzXiTh816mYwmWCeL17Ck8QOjxY2jYXnL5MHS77/LjlKYxi5xBVtQcdS4/eXR2E0ezbh8/P1/VsaNl2SeEVU1sHOVMZa6fzszHHsNHMNbsCgEt0FRPAy7vnYHfYuIsP2FsQhyd2kB1oqL/lsdQG8BVctExFpxBKYnGu8=
  - secure: MZ4QeabfHFQMBULkqvQBE3QWGDZMYlmnSlGC7icBF0ndZTxjYghXWsDu+f99kbGTnZy/N3EGSLhsuXzozFKp2rlAWZSPuyPAB8qx3auoFlDmzHKE9e/1UoE/Fakc6x2H0mzjdOu1bi+5yCrWVBMhac8UagRnuOhvhNCG9nQKfbg=
